on: [push]

jobs:
    codescan:
        runs-on: ubuntu-latest
        steps:
            # Checkout your code repository to scan
            -   name: Checkout repository
                uses: actions/checkout@v2
                with:
                    # We must fetch at least the immediate parents so that if this is
                    # a pull request then we can checkout the head.
                    fetch-depth: 2

            # If this run was triggered by a pull request event, then checkout
            # the head of the pull request instead of the merge commit.
            -   run: git checkout HEAD^2
                if: ${{ github.event_name == 'pull_request' }}

            -   name: Set up JDK 1.8
                uses: actions/setup-java@v1
                with:
                    java-version: 1.8

            -   name: Cache files
                uses: actions/cache@v2
                with:
                    path: |
                        ~/.m2
                        ~/.sonar
                    key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                    restore-keys: ${{ runner.os }}-m2

            -   name: Build with Maven
                run: mvn package -DskipTests

            -   name: Run Analysis
                uses: borisbsu/codescan-scanner-action@main
                with:
                    login: ${{ secrets.SONAR_LOCAL_TOKEN }}
                    organization: barys-o
                    projectKey: java-project
                    codeScanUrl: https://codescan.pagekite.me/
                    args: |
                        sonar.verbose=true
                        sonar.java.binaries=target
                        sonar.scanner.report.enabled=false
                        sonar.analysis.report.enabled=true
                        sonar.analysis.report.type=sarif

            -   name: Upload report-task.txt file
                uses: actions/upload-artifact@v2
                with:
                    name: report-task.txt
                    path: .scannerwork/report-task.txt

            -   name: Upload SARIF file
                uses: github/codeql-action/upload-sarif@v1
                with:
                    sarif_file: codescan.sarif
